// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6
// Source: user.proto

package server

import (
	"context"

	"goZeroStudy/3goZeroBasic/user/internal/logic"
	"goZeroStudy/3goZeroBasic/user/internal/svc"
	"goZeroStudy/3goZeroBasic/user/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

// 定义rpc方法
func (s *UserServer) GetUser(ctx context.Context, in *user.GetUserReq) (*user.GetUserResp, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

func (s *UserServer) Ping(ctx context.Context, in *user.GetUserReq) (*user.GetUserResp, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
