// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6

package types

type UserReq struct {
	Id string `form:"id"` //此处使用json标签无法访问服务
}

type UserResp struct {
	Id    string `json:"id"`
	Name  string `json:"name"`
	Phone string `json:"phone"`
}
